version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:3000"
    env_file:
      - ./frontend/.env.local

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env