version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=$NEXT_PUBLIC_BACKEND_URL
      - SUPABASE_URL=$SUPABASE_URL
      - SUPABASE_KEY=$SUPABASE_KEY

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - SUPABASE_URL=$SUPABASE_URL
      - SUPABASE_KEY=$SUPABASE_KEY
      - PINECONE_API_KEY=$PINECONE_API_KEY
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - BUCKET_NAME=$BUCKET_NAME